[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
nodaemon=true
user=root
childlogdir=/var/log/supervisor

# Run PHP-FPM
[program:php-fpm]
command=php-fpm
stdout_logfile=/var/log/supervisor/php-fpm.log
stderr_logfile=/var/log/supervisor/php-fpm-error.log
autorestart=true
autostart=true
priority=10
stdout_events_enabled=true
stderr_events_enabled=true

# Run Nginx
[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx-error.log
autorestart=true
autostart=true
priority=20
stdout_events_enabled=true
stderr_events_enabled=true

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
